const path = require("path");
const fs = require("fs");

const projectPackageJson = JSON.parse(fs.readFileSync(path.join(process.cwd(), "package.json"), "utf8"));

var template = {
	messages: {
		type: newMessage(
			"Select the type of change that you're committing:",
			"Selecione o tipo de mudança que você está commitando:"
		),
		scope: newMessage(
			"(Optional) Denote the SCOPE of this change:",
			"(Opcional) Indique o ESCOPO desta mudança:"
		),
		customScope: newMessage(
			"Denote the SCOPE of this change:",
			"Indique o ESCOPO desta mudança:"
		),
		subject: newMessage(
			"Write a SHORT, IMPERATIVE tense description of the CHANGE:\n",
			"Escreva uma mensagem CURTA e IMPERATIVA que descreve O QUE a sua mudança faz:\n"
		),
		body: newMessage(
			'(Optional) Provide a more DETAILED description of the change. Use "|" to break line:\n',
			'(Opcional) Forneça mais DETALHES sobre a mudança, como o PORQUÊ dela ter sido feita. Use "|" para pular linha:\n'
		),
		breaking: newMessage(
			'(Optional) List any BREAKING CHANGES. Use "|" to break line:\n',
			'(Opcional) Liste quaisquer BREAKING CHANGES. Use "|" para pular linha:\n'
		),
		footerPrefixesSelect: newMessage(
			"(Optional) Select the ISSUES type of changeList by this change:",
			"(Opcional) Selecione o tipo de ISSUES resolvido por esta mudança:",

		),
		customFooterPrefix: newMessage(
			"Insert ISSUES prefix:",
			"Insira o prefixo de ISSUES:"
		),
		footer: newMessage(
			"List any ISSUES by this change. E.g.: #31, #34:\n",
			"Liste quaisquer ISSUES que essa mudança resolve. Ex.: #31, #34:\n"
		),
		generatingByAI: newMessage(
			"Generating your AI commit subject...",
			"Gerando sua mensagem de commit por IA..."
		),
		generatedSelectByAI: newMessage(
			"Select the message generated by AI most suitable:",
			"Selecione a mensagem gerada pela IA mais adequada:"
		),
		confirmCommit: newMessage(
			"Are you sure you want to proceed with the commit above?",
			"Tem certeza de que deseja prosseguir com o commit acima?"
		)
	},
	types: [
		newType("feat", "✨", ":sparkles:",
			"Implementing a new feature.",
			"Implementando uma nova funcionalidade."
		),
		newType("feat", "📱", ":iphone:",
			"Working on responsive design.",
			"Trabalhando em design responsivo."
		),
		newType("feat", "💫", ":dizzy:",
		"Adding or updating animations and transitions.",
			"Adicionando ou atualizando animações e transições."
		),
		newType("feat", "🌐", ":globe_with_meridians:",
			"Internationalizing or localizing.",
			"Internacionalizando ou localizando."
		),
		newType("feat", "🚸", ":children_crossing:",
			"Improving user experience / usability.",
			"Melhorando a experiência do usuário / usabilidade."
		),
		newType("feat", "♿️", ":wheelchair:",
			"Improving accessibility.",
			"Melhorando a acessibilidade."
		),
		newType("feat", "🥚", ":egg:",
			"Adding or updating easter eggs.",
			"Adicionando ou atualizando um easter egg."
		),
		newType("experiment", "⚗️ ", ":alembic:",
			"Experimenting new things.",
			"Experimentando novas coisas."
		),
		newType("wip", "🚧", ":construction:",
			"Doing a work in progress.",
			"Fazendo um trabalho que está em andamento."
		),
		newType("breaking change", "💥", ":boom:",
			"Introducing BREAKING CHANGES.",
			"Introduzindo BREAKING CHANGES."
		),
		newType("fix", "🐛", ":bug:",
			"Fixing a bug.",
			"Corrigindo um bug."
		),
		newType("fix", "🖋️ ", ":fountain_pen:",
			"Fixing typos.",
			"Corrigindo erros de digitação que afetam o funcionamento do código."
		),
		newType("fix", "🥅", ":goal_net:",
			"Catching errors.",
			"Capturando erros."
		),
		newType("hotfix", "🚑", ":ambulance:",
			"Critical hotfix.",
			"Corrigindo falha crítica."
		),
		newType("security", "🔒", ":lock:",
			"Fixing security issues.",
			"Corrigindo problemas de segurança."
		),
		newType("lint", "🚨", ":rotating_light:",
			"Removing linter warnings.",
			"Removendo avisos do linter."
		),
		newType("types", "🏷️ ", ":label:",
			"Adding or updating types.",
			"Adicionando ou atualizando tipos de dados."
		),
		newType("performance", "⚡️", ":zap:",
			"Improving performance.",
			"Fazendo mudanças de código que melhoram o desempenho."
		),
		newType("deprecate", "🗑️ ", ":wastebasket:",
			"Deprecating code that needs to be cleaned up.",
			"Depreciando código que precisa ser limpo."
		),
		newType("style", "🎨", ":art:",
			"Improving structure / format of the code.",
			"Melhorando a estrutura / formato do código."
		),
		newType("style", "💄", ":lipstick:",
			"Updating the UI and style files.",
			"Fazendo mudanças que não afetam o significado do código."
		),
		newType("refactor", "♻️ ", ":recycle:",
			"Refactoring code.",
			"Refatorando código."
		),
		newType("refactor", "💩", ":poop:",
			"Writing bad code that needs to be improved.",
			"Escrevendo código ruim que precisa ser melhorado."
		),
		newType("refactor", "⚰️ ", ":coffin:",
			"Removing dead code.",
			"Removendo código morto."
		),
		newType("refactor", "👌", ":ok_hand:",
			"Updating code due to code review changes.",
			"Atualizando código devido a mudanças na revisão de código."
		),
		newType("refactor", "🚚", ":truck:",
			"Moving or renaming files.",
			"Movendo ou renomeando arquivos."
		),
		newType("add", "✨", ":sparkles:",
			"Adding new features.",
			"Adicionando códigos ou arquivos."
		),
		newType("remove", "🔥", ":fire:",
			"Removing code or files.",
			"Removendo códigos ou arquivos."
		),
		newType("chore", "⚙️ ", ":gear:",
			"Changing configuration files.",
			"Fazendo mudanças em arquivos de configuração."
		),
		newType("chore", "🚀", ":rocket:",
			"Deploying stuff.",
			"Fazendo deploy de coisas"
		),
		newType("test", "✅", ":white_check_mark:",
			"Adding missing tests or correcting existing tests.",
			"Adicionando testes ausentes ou corrigindo testes existentes."
		),
		newType("dependency", "👽", ":alien:",
			"Updating code due to external API changes.",
			"Atualizando o código devido às mudanças em APIs externas."
		),
		newType("dependency", "⬇️ ", ":arrow_down:",
			"Downgrading dependencies.",
			"Desatualizando dependências."
		),
		newType("dependency", "⬆️ ", ":arrow_up:",
			"Upgrading dependencies.",
			"Atualizando dependências."
		),
		newType("dependency", "➕", ":heavy_plus_sign:",
			"Adding a dependency.",
			"Adicionando dependência."
		),
		newType("dependency", "➖", ":heavy_minus_sign:",
			"Removing a dependency.",
			"Removendo dependência."
		),
		newType("build", "📦️", ":package:",
			"Changing build process, adding or updating compiled files or packages.",
			"Fazendo mudanças que afetam o sistema de build ou dependências externas."
		),
		newType("docs", "📚", ":books:",
			"Changing documentation.",
			"Fazendo mudanças apenas na documentação."
		),
		newType("docs", "💡", ":bulb:",
			"Documenting source code.",
			"Documentando o código fonte."
		),
		newType("docs", "✏️", ":pencil:",
			"Fixing typos in comments or documentation.",
			"Corrigindo erros de digitação em comentários ou documentações."
		),
		newType("docs", "👥", ":busts_in_silhouette:",
			"Adding or updating contributor(s).",
			"Adicionando ou atualizando contribuidor(es)."
		),
		newType("license", "📄", ":page_facing_up:",
			"Adding or updating license.",
			"Adicionando ou atualizando licença."
		),
		newType("merge", "🔀", ":twisted_rightwards_arrows:",
			"Merging branches.",
			"Mesclando branches."
		),
		newType("revert", "⏪️", ":rewind:",
			"Reverting changes.",
			"Revertendo mudanças."
		),
		newType("ignore", "🙈", ":see_no_evil:",
			"Adding or updating a .gitignore file.",
			"Adicionando ou atualizando um arquivo .gitignore."
		),
		newType("init", "🎉", ":tada:",
			"Doing initial commit.",
			"Fazendo o commit inicial"
		)
	],
	useEmoji: true,
	emojiAlign: "left",
	useAI: false,
	aiQuestionCB: undefined,
	aiNumber: 5,
	themeColorCode: "",
	scopes: [],
	allowCustomScopes: true,
	allowEmptyScopes: true,
	customScopesAlign: "bottom",
	customScopesAlias: "custom",
	emptyScopesAlias: "empty",
	upperCaseSubject: true,
	markBreakingChangeMode: false,
	allowBreakingChanges: ["feat", "fix"],
	breaklineNumber: 100,
	breaklineChar: "|",
	skipQuestions: [],
	issuePrefixes: undefined,
	customIssuePrefixAlign: "top",
	emptyIssuePrefixAlias: "skip",
	customIssuePrefixAlias: "custom",
	allowCustomIssuePrefix: true,
	allowEmptyIssuePrefix: true,
	confirmColorize: true,
	maxHeaderLength: Infinity,
	maxSubjectLength: 95,
	minSubjectLength: 10,
	scopeOverrides: undefined,
	defaultBody: "",
	defaultIssues: "",
	defaultScope: "",
	defaultSubject: ""
};

switch (projectPackageJson.config.language) {
	case "en-US":
		template.aiQuestionCB = ({maxSubjectLength, diff}) =>
			`Write an insightful and concise Git commit message in the present tense for the following Git diff code, without any prefixes, and no longer than ${maxSubjectLength} characters.: \`\`\`diff\n${diff}\n\`\`\``;
		template.issuePrefixes = [{value: "closed", name: "closed:   ISSUES has been processed" }];
		break;
		
	case "pt-BR":
		template.aiQuestionCB = ({maxSubjectLength, diff}) =>
			`Escreva uma mensagem de commit do Git perspicaz e concisa no tempo imperativo para o seguinte código de diff do Git, sem nenhum prefixo e não mais do que ${maxSubjectLength} caracteres.: \`\`\`diff\n${diff}\n\`\`\``;
		template.issuePrefixes = [{value: "closed", name: "closed:   ISSUES foram processados" }];
		break;
}

/*--------------------------------------------------------------------------------------------*/

function newType(value, emoji, github_emoji, name_enUS, name_ptBR) {
	let name;

	switch (projectPackageJson.config.language) {
		case "en-US":
			name = name_enUS;
			break;
			
		case "pt-BR":
			name = name_ptBR;
			break;
	}

	return {
		value: value,
		name: `${emoji} ` + name,
		emoji: github_emoji
	};
}

function newMessage(text_enUS, text_ptBR) {
	let text;

	switch (projectPackageJson.config.language) {
		case "en-US":
			text = text_enUS;
			break;
			
		case "pt-BR":
			text = text_ptBR;
			break;
	}

	return text;
}

/*--------------------------------------------------------------------------------------------*/

module.exports = template;